/**
 * @fileoverview AirNow response bodies captured from www.airnowapi.org on 2026-10-08,
 * verbatim, for the 2026 web services (`observation/current/ziplatlong/`,
 * `forecast/current/`). Each constant is the raw HTTP body text.
 * @module tests/services/airnow/airnow-fixtures
 */

/** `observation/current/ziplatlong/?zipCode=98101` — HTTP 200, three pollutants from two monitors. */
export const OBSERVATION_98101 = `[{"dateObserved":"2026-10-08","hourObserved":"03:00","localTimeZone":"PDT","reportingAreaName":"Seattle-Bellevue-Kent Valley","siteID":"530330030","siteName":"Seattle-10th & Weller","parameterName":"PM2.5","nowcastAQI":62,"aqiCategoryName":"Moderate","reportingAgency":"Washington Department of Ecology","lookupBehavior":"Closest Reading By Pollutant","consideredMonitors":"All","lookupBoundary":"50 Miles"},{"dateObserved":"2026-10-08","hourObserved":"03:00","localTimeZone":"PDT","reportingAreaName":"Seattle-Bellevue-Kent Valley","siteID":"530330080","siteName":"Seattle-Beacon Hill","parameterName":"OZONE","nowcastAQI":0,"aqiCategoryName":"Good","reportingAgency":"Washington Department of Ecology","lookupBehavior":"Closest Reading By Pollutant","consideredMonitors":"All","lookupBoundary":"50 Miles"},{"dateObserved":"2026-10-08","hourObserved":"03:00","localTimeZone":"PDT","reportingAreaName":"Seattle-Bellevue-Kent Valley","siteID":"530330080","siteName":"Seattle-Beacon Hill","parameterName":"PM10","nowcastAQI":12,"aqiCategoryName":"Good","reportingAgency":"Washington Department of Ecology","lookupBehavior":"Closest Reading By Pollutant","consideredMonitors":"All","lookupBoundary":"50 Miles"}]`;

/** `forecast/current/?zipCode=98101` — HTTP 200, five issued days with one shared discussion. */
export const FORECAST_98101 = `[{"dateIssue":"2026-10-07","dateValid":"2026-10-08","reportingArea":"Seattle-Bellevue-Kent Valley","reportingAreaCode":"wa004","stateCode":"WA","parameterName":"PM2.5","aqi":39,"forecastAgency":"Puget Sound Clean Air Agency","categoryNumber":1,"categoryName":"Good","actionDay":false,"discussion":"For Oct 7-12 (Wed-Mon): Expect GOOD to MODERATE air quality through early next week."},{"dateIssue":"2026-10-07","dateValid":"2026-10-09","reportingArea":"Seattle-Bellevue-Kent Valley","reportingAreaCode":"wa004","stateCode":"WA","parameterName":"PM2.5","aqi":39,"forecastAgency":"Puget Sound Clean Air Agency","categoryNumber":1,"categoryName":"Good","actionDay":false,"discussion":"For Oct 7-12 (Wed-Mon): Expect GOOD to MODERATE air quality through early next week."},{"dateIssue":"2026-10-07","dateValid":"2026-10-10","reportingArea":"Seattle-Bellevue-Kent Valley","reportingAreaCode":"wa004","stateCode":"WA","parameterName":"PM2.5","aqi":39,"forecastAgency":"Puget Sound Clean Air Agency","categoryNumber":1,"categoryName":"Good","actionDay":false,"discussion":"For Oct 7-12 (Wed-Mon): Expect GOOD to MODERATE air quality through early next week."},{"dateIssue":"2026-10-07","dateValid":"2026-10-11","reportingArea":"Seattle-Bellevue-Kent Valley","reportingAreaCode":"wa004","stateCode":"WA","parameterName":"PM2.5","aqi":53,"forecastAgency":"Puget Sound Clean Air Agency","categoryNumber":2,"categoryName":"Moderate","actionDay":false,"discussion":"For Oct 7-12 (Wed-Mon): Expect GOOD to MODERATE air quality through early next week."},{"dateIssue":"2026-10-07","dateValid":"2026-10-12","reportingArea":"Seattle-Bellevue-Kent Valley","reportingAreaCode":"wa004","stateCode":"WA","parameterName":"PM2.5","aqi":56,"forecastAgency":"Puget Sound Clean Air Agency","categoryNumber":2,"categoryName":"Moderate","actionDay":false,"discussion":"For Oct 7-12 (Wed-Mon): Expect GOOD to MODERATE air quality through early next week."}]`;

/** `forecast/current/?zipCode=60601` — HTTP 200, category-only forecast (`aqi: -1`), empty discussion. */
export const FORECAST_60601_CATEGORY_ONLY = `[{"dateIssue":"2026-10-07","dateValid":"2026-10-08","reportingArea":"Chicago","reportingAreaCode":"il001","stateCode":"IL","parameterName":"PM2.5","aqi":-1,"forecastAgency":"Illinois EPA","categoryNumber":1,"categoryName":"Good","actionDay":false,"discussion":""},{"dateIssue":"2026-10-07","dateValid":"2026-10-08","reportingArea":"Chicago","reportingAreaCode":"il001","stateCode":"IL","parameterName":"OZONE","aqi":-1,"forecastAgency":"Illinois EPA","categoryNumber":1,"categoryName":"Good","actionDay":false,"discussion":""},{"dateIssue":"2026-10-07","dateValid":"2026-10-09","reportingArea":"Chicago","reportingAreaCode":"il001","stateCode":"IL","parameterName":"PM2.5","aqi":-1,"forecastAgency":"Illinois EPA","categoryNumber":1,"categoryName":"Good","actionDay":false,"discussion":""},{"dateIssue":"2026-10-07","dateValid":"2026-10-09","reportingArea":"Chicago","reportingAreaCode":"il001","stateCode":"IL","parameterName":"OZONE","aqi":-1,"forecastAgency":"Illinois EPA","categoryNumber":1,"categoryName":"Good","actionDay":false,"discussion":""}]`;

/** `observation/current/ziplatlong/?latitude=30.0&longitude=-150.0` — HTTP 200, no monitors. */
export const OBSERVATION_NO_COVERAGE = `{"WebServiceError":[{"Message":"There are no observations available for the requested latitude/longitude: No observations were found for all monitors within 50 miles."}]}`;

/** `forecast/current/?latitude=30.0&longitude=-150.0` — HTTP 200, no reporting area. */
export const FORECAST_NO_REPORTING_AREA = `{"WebServiceError":[{"Message":"Error - There is no reporting area at your searched location"}]}`;

/** `forecast/current/?zipCode=99501` — HTTP 200, the area exists but issued no forecast. */
export const FORECAST_NONE_ISSUED_99501 = `{"WebServiceError":[{"Message":"Error - There are no current forecasts available for the requested reporting area: Anchorage, AK."}]}`;

/** `observation/current/ziplatlong/?zipCode=00000` — HTTP 400. */
export const INVALID_ZIP_400 = `{"WebServiceError":[{"Message":"Invalid zipCode provided"}]}`;
